name: Android-Clang
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
      CMAKE_INSTALL_DIR: ${{ github.workspace }}/install/
      CC: clang
      CXX: clang++
      ANDROID: true

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/cache@v2
        with:
          path: android-ndk-r18b
          key: ${{ runner.os }}-android-ndk

      - uses: lukka/get-cmake@latest

      - name: Generate project files
        run: |
          cmake -B "${{ env.CMAKE_BUILD_DIR }}" -DCMAKE_INSTALL_PREFIX="${{ env.CMAKE_INSTALL_DIR }}" -DCMAKE_DEBUG_POSTFIX=d

      - name: Build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target all --config Debug