name: Linux-Clang
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
      CMAKE_INSTALL_DIR: ${{ github.workspace }}/install/
      CC: clang
      CXX: clang++

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: lukka/get-cmake@latest

      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Generate project files
        run: |
          cmake -B "${{ env.CMAKE_BUILD_DIR }}" -DCMAKE_INSTALL_PREFIX="${{ env.CMAKE_INSTALL_DIR }}" -DCMAKE_DEBUG_POSTFIX=d -G "Unix Makefiles"

      - name: Build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target all --config Debug